name: Trigger auto deployment for itfest-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/itfest-app-AutoDeployTrigger-33829be4-df8b-490b-9ecf-c0a331aeb77d.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ITFESTAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.ITFESTAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.ITFESTAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: noburnoutacr.azurecr.io
          registryUsername: ${{ secrets.ITFESTAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ITFESTAPP_REGISTRY_PASSWORD }}
          containerAppName: itfest-app
          resourceGroup: itfestmicro
          imageToBuild: noburnoutacr.azurecr.io/itfest-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


